version: '3'



services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: videoflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on: 
      - db


