# Generated by Django 5.0.1 on 2024-02-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Action', 'Action'), ('Thriller', 'Thriller'), ('Horror', 'Horror'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('Animation', 'Animation'), ('Mystery', 'Mystery'), ('Documentary', 'Documentary'), ('Other', 'Other')], default='Other', max_length=32),
        ),
        migrations.AddField(
            model_name='video',
            name='poster_file',
            field=models.FileField(blank=True, null=True, upload_to='poster'),
        ),
    ]
