# Generated by Django 5.0.1 on 2024-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_genre_video_poster_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_480p_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/'),
        ),
    ]
