# Generated by Django 5.0.1 on 2024-02-22 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_video_480p_file_video_video_720p_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_480p_file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_720p_file',
        ),
    ]
